# Generated by Django 5.1.3 on 2024-11-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('site', models.URLField(max_length=255, verbose_name='Сайт')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.BooleanField(choices=[(True, 'Активен'), (False, 'Неактивен')], default=True, verbose_name='Статус')),
            ],
        ),
    ]
