# Generated by Django 5.1.3 on 2024-12-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='site',
        ),
    ]
