# Generated by Django 5.1.3 on 2024-12-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram',
            field=models.BooleanField(default=False, verbose_name='Телеграм'),
        ),
    ]
