# Generated by Django 5.1.3 on 2024-12-07 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token_auth',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Токен регистрации'),
        ),
    ]
