# Generated by Django 5.1.3 on 2024-12-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Почта')),
                ('password', models.CharField(max_length=75, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('administrator', 'Администратор'), ('business', 'Бизнес'), ('manager', 'Менеджер')], db_index=True, default='business', max_length=15, verbose_name='Роль')),
                ('user_active', models.BooleanField(choices=[(True, 'Активирован'), (False, 'Не активирован')], default=False, verbose_name='Активирован')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Название компании')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('telegram', models.BooleanField(db_index=True, default=False, verbose_name='Телеграм')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
