# Generated by Django 5.1.3 on 2024-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='accepted_rule',
            field=models.BooleanField(default=True, verbose_name='Политика конфиденциальности'),
            preserve_default=False,
        ),
    ]
