# Generated by Django 5.1.3 on 2024-12-12 12:33

import oktta.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusers_accepted_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Почта')),
                ('password', models.CharField(verbose_name='Пароль')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('accepted_rule', models.BooleanField(verbose_name='Правила конфиденциальности')),
                ('register_token', models.CharField(default=oktta.utils.generate_password, max_length=17, verbose_name='Ссылка-токен')),
            ],
        ),
    ]
