# Generated by Django 5.1.3 on 2024-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userregister_register_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='accepted_rule',
            field=models.BooleanField(default=False, verbose_name='Политика конфиденциальности'),
        ),
    ]
