# Generated by Django 5.1.3 on 2024-12-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('icon_mime_type', models.CharField(max_length=255)),
                ('greeting', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('header_color', models.CharField(max_length=255)),
                ('header_text_color', models.CharField(max_length=255)),
                ('background_color', models.CharField(max_length=255)),
                ('user_color', models.CharField(max_length=255)),
                ('user_text_color', models.CharField(max_length=255)),
                ('bot_color', models.CharField(max_length=255)),
                ('bot_text_color', models.CharField(max_length=255)),
                ('custom_css', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('mode', models.CharField(choices=[('bot', 'Бот'), ('human', 'Человек')], max_length=10, verbose_name='Режим')),
                ('is_close', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_key.apitoken', verbose_name='Токен')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('human', 'Человек')], max_length=10, verbose_name='Роль')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='Чат')),
            ],
        ),
    ]
