# Generated by Django 5.1.3 on 2024-12-03 11:33

import django.db.models.deletion
import token_key.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название токена')),
                ('token_limit', models.PositiveIntegerField(default=50000, verbose_name='Лимит токенов')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('last_used', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Последнее использование')),
                ('token_active', models.BooleanField(db_index=True, default=True, verbose_name='Активный токен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=36, verbose_name='Токен для активации')),
                ('expired', models.DateTimeField(default=token_key.models.time_expired, verbose_name='Дата истечения токена')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания токена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
